// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghstvcigcxyjmadrryre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoc3R2Y2lnY3h5am1hZHJyeXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTA3NTAsImV4cCI6MjA1OTg2Njc1MH0.qPL-rAG-iUORuU6UEpXWmSLOgcOiq8uJzd7Az7C8YF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);