// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msdyplwlueuuwgwubnty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZHlwbHdsdWV1dXdnd3VibnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTYzMjEsImV4cCI6MjA1OTI3MjMyMX0.dBLGmOhSxymnCRzOwPdo90kc825lW7pQWv7VvoPzMh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);